# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Post conversations archive
#'
#' Archives a conversation.
#'
#' @param channel ID of conversation to archive
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return `TRUE` (invisibly) for success.
#' @keywords internal
conversations_archive <- function(channel, token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.archive",
    method = "post",
    token = token,
    body = list(channel = channel)
  )
  stop("Implement proper return")
}

#' Post conversations close
#'
#' Closes a direct message or multi-person direct message.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_close <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.close",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations create
#'
#' Initiates a public or private channel-based conversation
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_create <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.create",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Get conversations info
#'
#' Retrieve information about a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:read`
#' @param channel Conversation ID to learn more about
#' @param include_locale Set this to `true` to receive the locale for this
#'   conversation. Defaults to `false`
#' @param include_num_members Set to `true` to include the member count for the
#'   specified conversation. Defaults to `false`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_info <- function(channel, include_locale, include_num_members, token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.info",
    method = "get",
    token = token,
    query = list(channel = channel, include_locale = include_locale, include_num_members = include_num_members)
  )
}

#' Post conversations invite
#'
#' Invites users to a channel.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_invite <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.invite",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations join
#'
#' Joins an existing conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `channels:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_join <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.join",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations kick
#'
#' Removes a user from a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_kick <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.kick",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations leave
#'
#' Leaves a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_leave <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.leave",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations mark
#'
#' Sets the read cursor in a channel.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_mark <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.mark",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Get conversations members
#'
#' Retrieve members of a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:read`
#' @param channel ID of the conversation to retrieve members for
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_members <- function(channel, max_results = Inf, max_reqs = Inf, cursor, token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.members",
    method = "get",
    token = token,
    query = list(channel = channel)
  )
}

#' Post conversations open
#'
#' Opens or resumes a direct message or multi-person direct message.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_open <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.open",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations rename
#'
#' Renames a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_rename <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.rename",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations set purpose
#'
#' Sets the purpose for a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_set_purpose <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.setPurpose",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations set topic
#'
#' Sets the topic for a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_set_topic <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.setTopic",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations unarchive
#'
#' Reverses conversation archival.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
conversations_unarchive <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.unarchive",
    method = "post",
    token = token,
    body = list(token = token)
  )
}
