# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Post conversations archive
#'
#' Archives a conversation.
#'
#' @param channel ID of conversation to archive
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return `TRUE` (invisibly) for success.
#' @keywords internal
slack_conversations_archive <- function(channel, token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.archive",
    method = "post",
    token = token,
    body = list(channel = channel)
  )
  stop("Implement proper return")
}

#' Post conversations close
#'
#' Closes a direct message or multi-person direct message.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_close <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.close",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations create
#'
#' Initiates a public or private channel-based conversation
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_create <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.create",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Get conversations history
#'
#' Fetches a conversation's history of messages and events.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:history`
#' @param channel (`character`) Conversation ID to fetch history for.
#' @param latest (`datetime` or `double`) End of time range of messages to
#'   include in results.
#' @param oldest (`datetime` or `double`) Start of time range of messages to
#'   include in results.
#' @param inclusive (`logical`) Include messages with `latest` or `oldest`
#'   timestamp in results only when either timestamp is specified.
#' @param include_all_metadata (`logical`) Return all metadata associated with
#'   this message.
#' @return A channel's messages as a tibble.
#' @export
slack_conversations_history <- function(channel,
                                        latest = lubridate::now(),
                                        oldest = 0,
                                        inclusive = TRUE,
                                        include_all_metadata = FALSE,
                                        max_results = Inf,
                                        max_reqs = Inf,
                                        token = Sys.getenv("SLACK_API_TOKEN")) {
  latest <- as_slack_ts(latest)
  oldest <- as_slack_ts(oldest)
  slack_call_api(
    path = "/conversations.history",
    method = "get",
    token = token,
    query = list(
      channel = channel,
      latest = latest,
      oldest = oldest,
      inclusive = inclusive,
      include_all_metadata = include_all_metadata
    ),
    pagination = "cursor",
    max_results = max_results,
    max_reqs = max_reqs
  )
}

#' Get conversations info
#'
#' Retrieve information about a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:read`
#' @param channel Conversation ID to learn more about
#' @param include_locale Set this to `true` to receive the locale for this
#'   conversation. Defaults to `false`
#' @param include_num_members Set to `true` to include the member count for the
#'   specified conversation. Defaults to `false`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_info <- function(channel, include_locale, include_num_members, token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.info",
    method = "get",
    token = token,
    query = list(channel = channel, include_locale = include_locale, include_num_members = include_num_members)
  )
}

#' Post conversations invite
#'
#' Invites users to a channel.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_invite <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.invite",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations join
#'
#' Joins an existing conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `channels:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_join <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.join",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations kick
#'
#' Removes a user from a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_kick <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.kick",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations leave
#'
#' Leaves a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_leave <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.leave",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Get conversations list
#'
#' Lists all channels in a Slack team.
#'
#' @param team_id (`character`) Encoded team id to list channels in, required if
#'   token belongs to org-wide app.
#' @param exclude_archived (`logical`) Set to `TRUE` to exclude archived
#'   channels from the list.
#' @param types (`character`) Mix and match channel types by providing a vector
#'   of any combination of `public_channel`, `private_channel`, `mpim`, `im`.
#'
#' @return A tibble of information about channels and channel-like
#'   conversations.
#' @export
slack_conversations_list <- function(team_id = NULL,
                                     exclude_archived = FALSE,
                                     types = c(
                                       "public_channel",
                                       "private_channel",
                                       "mpim",
                                       "im"
                                     ),
                                     max_results = Inf,
                                     max_reqs = Inf,
                                     token = Sys.getenv("SLACK_API_TOKEN")) {
  types <- rlang::arg_match(types, multiple = TRUE)
  slack_call_api(
    path = "/conversations.list",
    method = "get",
    token = token,
    query = list(
      team_id = team_id,
      exclude_archived = exclude_archived,
      types = types,
      .multi = "comma"
    ),
    pagination = "cursor",
    response_parser = .parse_channel,
    max_results = max_results,
    max_reqs = max_reqs
  )
}

#' Post conversations mark
#'
#' Sets the read cursor in a channel.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_mark <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.mark",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Get conversations members
#'
#' Retrieve members of a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:read`
#' @param channel ID of the conversation to retrieve members for
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_members <- function(channel, max_results = Inf, max_reqs = Inf, cursor, token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.members",
    method = "get",
    token = token,
    query = list(channel = channel)
  )
}

#' Post conversations open
#'
#' Opens or resumes a direct message or multi-person direct message.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_open <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.open",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations rename
#'
#' Renames a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_rename <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.rename",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Get conversations replies
#'
#' Retrieve a thread of messages posted to a conversation
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:history`
#' @param channel (`character`) Conversation ID to fetch thread from.
#' @param ts (`character` or `datetime` or `double`) Unique identifier of either
#'   a thread’s parent message or a message in the thread. ts must be the
#'   timestamp of an existing message with 0 or more replies. If there are no
#'   replies then just the single message referenced by ts will return - it is
#'   just an ordinary, unthreaded message.
#' @param latest (`datetime` or `double`) Only messages before this Unix
#'   timestamp will be included in results.
#' @param oldest (`datetime` or `double`) Only messages after this Unix
#'   timestamp will be included in results.
#' @param inclusive (`logical`) Include messages with `latest` or `oldest`
#'   timestamp in results only when either timestamp is specified.
#' @param include_all_metadata (`logical`) Return all metadata associated with
#'   this message.
#' @return A thread of messages posted to a conversation as a tibble. Note: The
#'   parent message is always included in the response.
#' @export
slack_conversations_replies <- function(channel,
                                        ts,
                                        latest = lubridate::now(),
                                        oldest = 0,
                                        inclusive = TRUE,
                                        include_all_metadata = FALSE,
                                        max_results = Inf,
                                        max_reqs = Inf,
                                        token = Sys.getenv("SLACK_API_TOKEN")) {
  latest <- as_slack_ts(latest)
  oldest <- as_slack_ts(oldest)
  slack_call_api(
    path = "/conversations.replies",
    method = "get",
    token = token,
    query = list(
      channel = channel,
      ts = ts,
      latest = latest,
      oldest = oldest,
      inclusive = inclusive,
      include_all_metadata = include_all_metadata
    ),
    pagination = "cursor",
    max_results = max_results,
    max_reqs = max_reqs
  )
}

#' Post conversations set purpose
#'
#' Sets the purpose for a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_set_purpose <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.setPurpose",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations set topic
#'
#' Sets the topic for a conversation.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_set_topic <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.setTopic",
    method = "post",
    token = token,
    body = list(token = token)
  )
}

#' Post conversations unarchive
#'
#' Reverses conversation archival.
#'
#' @param token (`character`) A bearer token provided by Slack. A later
#'   enhancement will add the ability to generate this token. Slack token are
#'   long-lasting, and should be carefully guarded. Requires scope:
#'   `conversations:write`
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @keywords internal
slack_conversations_unarchive <- function(token = Sys.getenv("SLACK_API_TOKEN")) {
  slack_call_api(
    path = "/conversations.unarchive",
    method = "post",
    token = token,
    body = list(token = token)
  )
}
