# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get users conversations
#'
#' List conversations the calling user may access.
#'
#' @inheritParams slack_call_api
#' @param user Browse conversations by a specific user ID's membership. Non-public channels are restricted to those where the calling user shares membership.
#' @param types Mix and match channel types by providing a comma-separated list of any combination of `public_channel`, `private_channel`, `mpim`, `im`
#' @param exclude_archived Set to `true` to exclude archived channels from the list
#' @param limit The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the list hasn't been reached. Must be an integer no larger than 1000.
#' @param cursor Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request's `response_metadata`. Default value fetches the first "page" of the collection. See [pagination](/docs/pagination) for more detail.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
users_conversations <- function(user, types, exclude_archived, limit, cursor, token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/users.conversations",
    method = "get",
    token = token,
    query = list(user = user, types = types, exclude_archived = exclude_archived, limit = limit, cursor = cursor)
  )
}

#' Post users delete photo
#'
#' Delete the user profile photo
#'
#' @inheritParams slack_call_api
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
users_delete_photo <- function(token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/users.deletePhoto",
    method = "post",
    token = token
  )
}

#' Get users get presence
#'
#' Gets user presence information.
#'
#' @inheritParams slack_call_api
#' @param user User to get presence info on. Defaults to the authed user.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
users_get_presence <- function(user, token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/users.getPresence",
    method = "get",
    token = token,
    query = list(user = user)
  )
}

#' Get users identity
#'
#' Get a user's identity.
#'
#' @inheritParams slack_call_api
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
users_identity <- function(token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/users.identity",
    method = "get",
    token = token
  )
}

#' Get users lookup by email
#'
#' Find a user with an email address.
#'
#' @inheritParams slack_call_api
#' @param email An email address belonging to a user in the workspace
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
users_lookup_by_email <- function(email, token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/users.lookupByEmail",
    method = "get",
    token = token,
    query = list(email = email)
  )
}

#' Post users set active
#'
#' Marked a user as active. Deprecated and non-functional.
#'
#' @inheritParams slack_call_api
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
users_set_active <- function(token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/users.setActive",
    method = "post",
    token = token
  )
}

#' Post users set photo
#'
#' Set the user profile photo
#'
#' @inheritParams slack_call_api
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
users_set_photo <- function(token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/users.setPhoto",
    method = "post",
    token = token
  )
}

#' Post users set presence
#'
#' Manually sets user presence.
#'
#' @inheritParams slack_call_api
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
users_set_presence <- function(token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/users.setPresence",
    method = "post",
    token = token
  )
}
