# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get api test
#'
#' Checks API calling code.
#'
#' @inheritParams slack_call_api
#' @param error Error response to return
#' @param foo example property to return
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
slack_api_test <- function(error, foo, token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/api.test",
    method = "get",
    token = token,
    query = list(error = error, foo = foo)
  )
}
