# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions. Missing documentation is tagged with "BKTODO" to make it easier for
# you to search for issues.

#' Get auth revoke
#'
#' Revokes a token.
#'
#' @inheritParams slack_call_api
#' @param test Setting this parameter to `1` triggers a _testing mode_ where the specified token will not actually be revoked.
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
slack_auth_revoke <- function(test, token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/auth.revoke",
    method = "get",
    token = token,
    query = list(test = test)
  )
}

#' Get auth test
#'
#' Checks authentication &amp; identity.
#'
#' @inheritParams slack_call_api
#' @return BKTODO: Return descriptions are not yet implemented in beekeeper
#' @export
slack_auth_test <- function(token = Sys.getenv("SLACK_TOKEN")) {
  slack_call_api(
    path = "/auth.test",
    method = "get",
    token = token
  )
}
